export enum EstadoEvento {
  PENDIENTE = 'PENDIENTE',
  EN_PROCESO = 'EN_PROCESO',
  APROBADO = 'APROBADO',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO',
  RECHAZADO = 'RECHAZADO',
  ANULADO = 'ANULADO',
}

export enum OrigenCreacionEvento {
  FORMULARIO_WEB = 'FORMULARIO_WEB',
  INTERCONEXION_PJUD = 'INTERCONEXION_PJUD',
}

export enum ParaQuien {
  CONDENADO = 'CONDENADO',
  VICTIMA = 'VICTIMA',
}

export enum TipoRelacion {
  GENERA_PROCESO = 'GENERA_PROCESO',
  REAGENDA = 'REAGENDA',
  GENERA_SOLICITUD = 'GENERA_SOLICITUD',
}

export enum EstadoAgenda {
  EN_PROCESO = 'EN_PROCESO',
  NO_REALIZADO = 'NO_REALIZADO',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO',
}

export enum MaquinaEstados {
  PROCESO = 'PROCESO',
  RESOLUCION = 'RESOLUCION',
  RESOLUCION_CON_VALIDACION = 'RESOLUCION_CON_VALIDACION',
}
