export enum EstadoEvento {
  PENDIENTE = 'PENDIENTE',
  EN_PROCESO = 'EN_PROCESO',
  APROBADO = 'APROBADO',
  COMPLETADO = 'COMPLETADO',
  CANCELADO = 'CANCELADO',
  RECHAZADO = 'RECHAZADO',
  ANULADO = 'ANULADO',
}

export enum OrigenCreacionEvento {
  FORMULARIO_WEB = 'FORMULARIO_WEB',
  INTERCONEXION_PJUD = 'INTERCONEXION_PJUD',
}

export enum ParaQuien {
  CONDENADO = 'CONDENADO',
  VICTIMA = 'VICTIMA',
}
